services:
  db:
    container_name: "backend-api-db"
    image: postgres:15.1-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data: